### ISSUE TITLE
Update Necessary documentation from the Besu HotFix

### ISSUE THREAD

**Issue by MadeofTin** [ethereum-cat-herders/PM#102]
Note to address the documentation that lead to a bug fixing release of Besu. Implementation of SELF_BALANCE was not self-evident and clarifying would lead to client implementations not running into the same problem.

**Comment by BuHeP** [comment]
> Note to address the documentation that lead to a bug fixing release of Besu. Implementation of SELF_BALANCE was not self-evident and clarifying would lead to client implementations not running into the same problem.

**Comment by MadeofTin** [comment]
It should be something that is updated in the Yellow paper. Or somewhere.

The specification wasn't clear which lead to confusion by a client team. Not a big thing, but worth putting in a list somewhere of Nice to haves for the yellow paper when someone gets around to updating the specifications.
