### ISSUE TITLE
Add an option to Ethernodes that accounts for "In process"

### ISSUE THREAD

**Issue by MadeofTin** [ethereum-cat-herders/PM#103]
When doing outreach on Muir glacier, a common responses are, 

 - "We are aware, and have someone working on it. We will get back to you when the upgrade has finished"
 - "We are aware, and have someone scheduled to update at X date"

It would be great to be able to reference them as being "In process". Meaning they have confirmed they will upgrade. Something to remember for next time, so I am putting a note here.

**Comment by Souptacular** [comment]
This is done.

**Comment by Souptacular** [comment]
Actually let's get clarification about if this is done from @MadeofTin.

**Comment by MadeofTin** [comment]
This one will be great when Berlin happens. But can wait until then.

**Comment by Souptacular** [comment]
Wait until Berlin is closer to ask Peter from Ethernodes about this.

**Comment by poojaranjan** [comment]
Berlin upgrade - https://www.ethernodes.org/berlin

**Comment by poojaranjan** [comment]
Berlin can be tracked with the web link provided.
