### ISSUE TITLE
Update Forkmon and publish Code Properly

### ISSUE THREAD

**Issue by MadeofTin** [ethereum-cat-herders/PM#104]
https://gitter.im/ethereum/AllCoreDevs?at=5e0dafceeaa2cd096fdea7ac

Update Forkmon
Add Additional Clients
Move it to the right repo.

Additional notes in the ACD Gitter.

**Comment by poojaranjan** [comment]
https://forkmon.ethdevops.io/ is up.

**Comment by Souptacular** [comment]
It's updated now. Closing.
