### ISSUE TITLE
Steps to be done if we want to see ProgPoW live with Istanbul hardfork 

### ISSUE THREAD

**Issue by sneg55** [ethereum-cat-herders/PM#11]
Copy pasted it from Gitter/ Eth-magicians

## Steps to be done if we want to see ProgPoW live with Istanbul hardfork 

(1) get money into the audit bounties. 
(2) Then the audit needs to come back with corroborating results 
(3) then it gets added to the next hard fork (Istanbul if it happens soon enough) 
(4) then the hardfork happens.

The bounty that has to be funded for ProgPoW audit:   
https://gitcoin.co/grants/82/official-progpow-technical-audit-funding 
we need to fundraise $50k for Least Authority audit 

---
Additional information: 
https://github.com/ethereum/EIPs/pull/1804
https://eips.ethereum.org/EIPS/eip-1679 
https://en.ethereum.wiki/roadmap/Istanbul
https://www.reddit.com/r/ethereum/comments/b49c26/clarification_on_the_acceptance_of_progpow_into_a/ 
https://medium.com/ethereum-cat-herders/progpow-audit-goals-expectations-75bb902a1f01

**Comment by sneg55** [comment]
@Souptacular  can you please take a look when you have time?

**Comment by lookfirst** [comment]
@sneg55 

The old bounty ended (dead) and the new bounty is here:

https://explorer.bounties.network/bounty/2502

Yes, confusing. Sorry.

**Comment by brentxu** [comment]
Apologies for confusion.  Yes this is the correct link:  

https://explorer.bounties.network/bounty/2502

We will post an official announcement including methodologies next week.  Thanks for everyone's patience on this.  We are taking steps to ensure that the tests are as comprehensive as possible.

**Comment by lookfirst** [comment]
@poojaranjan This one is important to discuss too!

**Comment by poojaranjan** [comment]
> @poojaranjan This one is important to discuss too!

Yes, I agree. Officially, I am not part of 'ProgPOW' subcommittee,  but as an ECH and a member of subcommittee for Hardfork Release manager, I hope this to be taken up soon. Next ECH call will provide more clarity.

**Comment by timbeiko** [comment]
This was discussed on the Cat Herders call today, and the next step is to see whether we can have the EIP be accepted conditional on the results of the audit for Istanbul. I've requested this to be added to the next AllCoreDevs agenda. https://github.com/ethereum/pm/issues/83#issuecomment-472035024

**Comment by timbeiko** [comment]
This was discussed on the Cat Herders call today, and the next step is to see whether we can have the EIP be accepted conditional on the results of the audit for Istanbul. I've requested this to be added to the next AllCoreDevs agenda. ethereum/pm#83 (comment)

**Comment by salanki** [comment]
@timbeiko: Thank you for your effort. I believe clear commitments, in the form of an accepted EIP under the pretense that "unless the audit comes back with red flags we will include ProgPoW" and a defined roadmap will make the community effort much easier. It's hard to get community funding together when the perception is that there are no clear goalposts.

**Comment by timbeiko** [comment]
@sneg55 I suggest you listen to today's AllCoreDevs call. It seems like there is some rough consensus about next steps. If you feel something specific is still missing for ProgPow, could you please highlight it? If not, can you close this issue? Thank you!

**Comment by lookfirst** [comment]
@timbeiko Would you like to please outline the rough consensus here in this issue as you see it?

**Comment by timbeiko** [comment]
To me (I could be wrong!) it seems that ProgPow is likely going to be implemented for Istanbul and may be pulled out if the audit reveals anything nasty. One action item that came out of the call was for the Cat Herders to nominate a point person for ProgPow. I tweeted a bit about it here: https://twitter.com/TimBeiko/status/1106557972250050562

I would really recommend watching that part of the call to get a better feel for things.

**Comment by sneg55** [comment]
@timbeiko  Thanks! I've watched it live, and I don't feel that this is set in stone consensus. I'll rather wait for Cat Herders confirmation on this steps, before closing this issue.

**Comment by lookfirst** [comment]
I was on the call. The discussion around ProgPoW felt like an unorganized mess, such to the point that Vitalik had to step in (rightfully) and shut it down. The request for a point person is because of this. The Cats (or point person) could have better prepared Hudson for the discussion.

There could have been a clearly defined set of talking points and things to agree on, yet Hudson was going on and on about ASICs, benchmarking and signals... all of which has been covered ad nauseam. Thankfully Danno mentioned the security aspect, which is really what we need whiteblock or whatever company for.

The analysis company hasn't been figured out yet either. Funding for Andrea and the analysis needs to be dealt with too. It isn't even clear if it'll happen in Istanbul or a separate fork based on what Alesky and Martin were saying.

So yea, keep this issue open please.

**Comment by bmann** [comment]
@Souptacular as discussed on core devs call, please let everyone know who the point of contact is for the audit process ( you, until you let us know different :) ), and what the terms of the audit are.

As I understand it from Core Devs call, the scope of the audit should be a technical and security review.

ASIC implementation etc is left as an exercise to the market.

**Comment by gcolvin** [comment]
https://www.roadtrips.com/wp-content/uploads/2016/11/kentuckyderby-hero7.jpg

**Comment by lrettig** [comment]
I think the non-technical aspects of progpow should be dropped entirely from the core devs agendas unless/until there's a technical update. As we lack another governance mechanism to discuss non-technical issues, I propose progpow remain wholly under the purview of the herders for the time being.

BTW the topic was discussed [here](https://github.com/ethereum/pm/blob/e48abcb8ab4e4eb82e93fb53a103d875c9854bf5/All%20Core%20Devs%20Meetings/Meeting%2057.md#13-progpow-update) on the last all core devs call.

**Comment by bmann** [comment]
@lrettig yes that’s agreed — now everyone is looking who the point of contact is from ECH. If it’s not you and it’s not @Souptacular then who is the human driving this?

**Comment by lrettig** [comment]
It's not me. I can't speak to anyone else.

**Comment by lookfirst** [comment]
![image](https://user-images.githubusercontent.com/85355/54576369-6a0f9a00-4a2a-11e9-9b35-a53a57b387ad.png)

"It's not me. I can't speak to anyone else. But, I will follow up with the rest of the Cats and get back to you with an answer as soon as we can."

-- Helpful Cat Herder.

**Comment by sneg55** [comment]
I was under impression that the Ethereum Cat Herders was created to avoid such chaos when nobody wants to take responsibility and nobody knows who is in charge?

**Comment by lrettig** [comment]
Fair game. I responded that way because @souptacular has run point on this for some time and I've intentionally stayed out of it. Will discuss with Hudson.

**Comment by timbeiko** [comment]
This is probably worth noting here: there will be talk of ProgPow (and all other potential Istanbul EIPs) at an in-person core devs meeting on April 17-18. https://ethereum-magicians.org/t/istanbul-eth1x-roadmap-planning-meeting-april-17th-18th-in-berlin/2899

**Comment by Souptacular** [comment]
I am the point person for this and will be releasing an update soon. We are currently trying to secure funding before we jump the gun on announcing the details of the audit. I can post some of them here though, or at least post what we hope can be accomplished from the audit pending funding and other things.

1. **The expected effects of ProgPoW on the security of Ethereum vis-a-vis:** 

- Security of the algorithm
- Attack surface
- Cost of 51% attack
- Other security risks that may result from a change from Ethash to ProgPoW 

2. **ProgPoW meeting the claimed goal of ASIC resistance**  

- Known methods to speed up the calculation of the hash function  
- Length of time it would it take to create a ProgPoW ASIC (if R&D begins immediately)
- Expected efficiency gains from the first generation of said ASICs

3. **Identify any potential advantages or disadvantages that ProgPoW would present in comparison to Ethash in terms of changes to network, “fair mining” and evaluate any potential uneven distribution.**

**Comment by shemnon** [comment]
Is there a timeframe on availability of findings that can be stated publicly?

**Comment by Souptacular** [comment]
> Is there a timeframe on availability of findings that can be stated publicly?

Not until we finalize and fund the audit details.

**Comment by lookfirst** [comment]
@Souptacular Any news on this?

**Comment by lookfirst** [comment]
https://medium.com/@lookfirst/what-is-the-total-amount-necessary-to-fund-the-audit-c2451efbcce5

**Comment by sneg55** [comment]
Quote from today meeting notes: 

> Hudson: Nay sayers don't see why we needed it. This is valid point. After the audit we can discuss it. Whiteblock are shutting down the bounties page as they will not be persuing the review of ProgPoW. Should look to community sentiment.

https://github.com/ethereum-cat-herders/PM/blob/master/All%20Ethereum%20Cat%20Herder%20Meetings/Meeting%208.md 

Can you please clarify this point? Could this community sentiment measurement lead to rejection of ProgPow EIP?

**Comment by salanki** [comment]
I’d also like to understand this. Community signaling was done using multiple media. It clearly showed support for ProgPoW. Most people who participated have now moved on as they have done their part. Do we need to keep remind the people who voted in the earlier signaling to “keep shouting” as decisions will be revered based on “who shouts the loudest at the moment”?

We have asked for a clear roadmap to ProgPoW to be able to get miners to fund the audit. This happened on Friday, and I was confident based on the statements made then that we will get this funded. If ProgPoW implementation reverts back to “Fund the audit and we will see what the community sentiment is”

**Comment by shemnon** [comment]
Community sentiment may shift based on audit results.  Heck, miner sentiment may shift based on the audit results.  But IMHO we should only change course if the sentiment shifts because available information changed.

**Comment by salanki** [comment]
Thank you and I agree 100% @shemnon
