### ISSUE TITLE
Renew Zoom pro account?

### ISSUE THREAD

**Issue by lrettig** [ethereum-cat-herders/PM#115]
It expires on May 1, i.e., at the end of this month. The basic renewal price is USD $149.90 (there's a chance we may qualify for some sort of non-profit discount). Do we want to renew it? If so, I'm happy to leave it on my personal credit card, or to let someone else pay.

**Comment by Souptacular** [comment]
I think we should renew. Open to other opinions though.

**Comment by timbeiko** [comment]
+1.

**Comment by poojaranjan** [comment]
Yeah, I think it's helpful. We should renew it.

**Comment by lrettig** [comment]
Okay. Does someone else want to pay for it, or shall I leave it on my personal credit card?

**Comment by timbeiko** [comment]
@lrettig probably simplest to have your CC and we pay you back in DAI. Does that work?

**Comment by Souptacular** [comment]
Closing. Zoom is renewed and paid for.
