### ISSUE TITLE
Converting SAI to DAI/USDC

### ISSUE THREAD

**Issue by Souptacular** [ethereum-cat-herders/PM#118]
I'm going ahead with this plan of taking out all of the SAI, converting it all to DAI, then converting 1/3 of that to USDC.

The multisig tx #74 has been generated to withdraw 5,364.66 SAI to 0xFbb5bA9B6A35E292C628a1b2809c6058c7Ac04b2 (an address I control)from our multisig address 0x68085E7f88e90Fa9247489C83fAB30b177Ebccb3. On the Gnosis safe website our SAI is listed as DAI because we haven't upgraded our safe.

**Comment by timbeiko** [comment]
@Souptacular confirmation sent: https://etherscan.io/tx/0xdf9f6ad65cd385e4e40d4ad4ac1891fc14dbcd58ed6e30224c04735cd2240b27

**Comment by Souptacular** [comment]
On April 23rd I completed the trading between SAI and DAI/USDC
Current DAI: 3386.599 DAI
Current SAI: 1723.796 USDC
Total Stablecoins: 5,110.395 

Started with 5364.66 SAI
Total Lost in Trades: 254.265  SAI

Address: 0xFbb5bA9B6A35E292C628a1b2809c6058c7Ac04b2
https://etherscan.io/address/0xfbb5ba9b6a35e292c628a1b2809c6058c7ac04b2

We are looking to upgrade our Gnosis safe next.

**Comment by Souptacular** [comment]
I have sent 100 USDC and 100 DAI to the new Gnosis Safe located at 0x02Cb3C150BEdca124d0aE8CcCb72fefbe705c953.

**Comment by timbeiko** [comment]
@Souptacular should we try and pay out some notes with that 500 DAI to be sure everything works smoothly?

**Comment by Souptacular** [comment]
@timbeiko we sucessfully paid 400 DAI worth of notes so the new multi-sig safe is well tested.

I have successfully sent the remainder of the DAI and USDC (2,886.5995 DAI and 1,673.797 USDC) I had in my possession to the new Gnosis multi-sig. 

https://etherscan.io/tx/0x32d61181b7ef52f6e71a5bc212e4132c04ae707c82b96774d566c8efa4338e51
https://etherscan.io/tx/0xf14bfbdb497794ac594e52d0ba8ee4ea780d862bc055ace4e18f93b9c0fc1872

Next step is to to move the assets from our old mult-sig to the new Gnosis safe. The two main assets we want to move is DAI and DATA. I tried moving them from the old to new mutli-sig and the contract interactions failed. I'm not sure why.

https://gnosis-safe.io/app/#/safes/0x02Cb3C150BEdca124d0aE8CcCb72fefbe705c953/balances

**Comment by Souptacular** [comment]
We have one last transaction in our old multi-sig that someone needs to approve so we can move 9 DAI left in it. https://wallet.gnosis.pm/#/wallet/0x68085E7f88e90Fa9247489C83fAB30b177Ebccb3

After that we can officially close this issue and use the new gnosis safe.

**Comment by Souptacular** [comment]
We need to transfer the 0.14 ETH out of the wallet, but the transaction displays an error message. I messaged someone from the Gnosis team to work with me on it.

**Comment by timbeiko** [comment]
I got an error too last night when trying to execute the transaction.

**Comment by Souptacular** [comment]
It turns out that the UI in Gnosis Wallet was saying we had 0.14 ETH when we had ~0.138 and it was rounding up. Once I fixed it to be the correct amount it worked! We can finally close this issue and ignore the old Gnosis Wallet unless there are ever any airdrops.
