### ISSUE TITLE
Document the cat herders process

### ISSUE THREAD

**Issue by lookfirst** [ethereum-cat-herders/PM#12]
In Gitter:

> @lrettig We are all drowning in too many channels and too much communication. I really cannot keep up with all of the dialog in this channel (or most other channels, for that matter)

I personally think that everyone is in agreement on this and would love to work to help improve things. The community just needs some direction. Just having meetings isn't enough. There needs to be an overall process and flow. I'd argue to also reduce the number of channels.

This is an issue to better document the cat herders PM process (in no particular order):

1. Define the flow necessary in order to better communicate effectively.
1. Work to lower the information overload.
1. Take ownership of the process.
1. Own the flow of information.
1. Provide guidance to new members.
1. Lower barriers to entry.
1. Reduce duplicated information.
1. Define the members of the cats and their roles.
1. Provide transparency.

I'm sure there is more, but this is a few things that I see as necessary in a PM role. I'm also clearly not saying 'how' to do this, I will leave that up to the cat herders.

**Comment by poojaranjan** [comment]
We hope to discuss this in our next ECH call on Tuesday, March 12th, 2019.

**Comment by ltfschoen** [comment]
I just finished creating this PR https://github.com/ethereum-cat-herders/PM/pull/13 associated with #12

**Comment by lookfirst** [comment]
When I wrote the above, I didn't imagine that process to be something Dilbert-esque like ISO 9001:2000. I was envisioning something that started off simple and is filled out and grows over time iteratively and by the community. I think that going down the route of an ISO will produce a lot of documentation that nobody reads and only follows when there is issues.

Seriously, there is a [slew of Dilbert cartoons about ISO 9000](https://www.google.com/search?q=dilbert+iso+9001&newwindow=1&source=lnms&tbm=isch&sa=X&ved=0ahUKEwih8Nfd-4DhAhUjGaYKHcEKCIkQ_AUIDigB&biw=1651&bih=948). Please don't be Dilbert.

![image](https://user-images.githubusercontent.com/85355/54335037-58a94500-465a-11e9-8c56-27e9c1081f52.png)

**Comment by adamschmideg** [comment]
I see the [Gitlab handbook](https://about.gitlab.com/handbook/handbook-usage/#why-handbook-first) a positive example. It's a few 1000 pages long. They seem to keep it up-to-date, because they actually use it for their day to day work.

**Comment by timbeiko** [comment]
Do we think this is still necessary? At the very least, it would be worth agreeing on what processes have to be defined. So far, everything seems to have ran fine-ish in a mostly ad-hoc way. What do you think @poojaranjan @lookfirst @ltfschoen ?

**Comment by lookfirst** [comment]
Most of the points above are still questions in my mind. Ad-hoc is lacking a sense of professionalism, that I would hope a group like this would have.

**Comment by ltfschoen** [comment]
I'd love to jump into this conversation again more seriously from August.

**Comment by timbeiko** [comment]
Cool, let's leave this open, then. It may make sense to have an agenda item on a call somewhere around August. I know there are plans for a ECH f2f at Berlin Blockchain Week, so it may be a good thing to discuss in person as well :-)

**Comment by poojaranjan** [comment]
Also adding [Contribution Guideline](https://github.com/ethereum-cat-herders/PM/blob/e74acbc4bab14d79667cf68f063a3dc543f46f16/Contribution_Guidelines.md) for community to participate. 


> I'd love to jump into this conversation again more seriously after August 2019.

@ltfschoen That would be really nice.

> Cool, let's leave this open, then. It may make sense to have an agenda item on a call somewhere around August. I know there are plans for a ECH f2f at Berlin Blockchain Week, so it may be a good thing to discuss in person as well :-)

@timbeiko Agreed. IMHO we should start inviting people relevant to issue to ECH calls for discussion in order to close them.

**Comment by timbeiko** [comment]
@ltfschoen do you still want to move this initiative forward?

**Comment by ltfschoen** [comment]
@timbeiko sure, I'm just short of time and not across everything. I'd need to pair with someone more across everything

**Comment by Souptacular** [comment]
Closing issue per meeting decision. Please create a new issue if you feel that it isn't complete.
