### ISSUE TITLE
Add links to previous calls to README

### ISSUE THREAD

**Issue by lrettig** [ethereum-cat-herders/PM#15]
Here are the ones I know about. Please add others that are missing:

- Meeting 7 (#8): https://www.youtube.com/watch?v=Va2fdfH5lic
- Meeting 6 (#6): https://youtu.be/TcWY8vmdh-k
- Meeting 5 (#4): https://youtu.be/tBnDcnAbdYo
- Meeting 4 (#3): https://soundcloud.com/lane-rettig-154644600/ethereum-cat-herders-meeting-4, https://youtu.be/1idlBHNGzqA
- Meeting 3 (Jan. 22 - no agenda?): https://youtu.be/e1_MadD8tAU

**Comment by DBrettRobertson** [comment]
Done.

**Comment by lrettig** [comment]
Thanks! In future let's use PRs so we have an audit log of changes and approvals of changes.
