### ISSUE TITLE
Notes for Ethereum 1559 community call

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/PM#163]
**Task** - Document notes for [Ethereum 1559 community call](https://youtu.be/EdXhL6VR0mU)

**Bounty** - 150 DAI

**Guidelines & template** - https://github.com/ethereum-cat-herders/PM/blob/master/Meeting_Notes_Template.md

Create a [Pull Request here](https://github.com/ethereum-cat-herders/PM/pulls) to submit the notes.

**Comment by shanelightowler** [comment]
Happy to do this @poojaranjan !

**Comment by poojaranjan** [comment]
PR: https://github.com/ethereum/pm/pull/272

**Comment by poojaranjan** [comment]
Notes submitted, payment successful.
