### ISSUE TITLE
Bounty for documenting meeting notes 

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/PM#170]
Task - Document notes for Ethereum ACD meeting 110

Bounty - 150 DAI

Guidelines & template - https://github.com/ethereum-cat-herders/PM/blob/master/Meeting_Notes_Template.md

Create a Pull Request [here](https://github.com/ethereum/pm/pulls) to submit the notes.

**Comment by shanelightowler** [comment]
Just to update, this is currently being worked on by a new ECH member and is close to delivery.

**Comment by shanelightowler** [comment]
PR raised: https://github.com/ethereum/pm/pull/317

**Comment by poojaranjan** [comment]
Thanks for your work. Bounty awarded!
