### ISSUE TITLE
Istanbul Hardfork Tracker

### ISSUE THREAD

**Issue by timbeiko** [ethereum-cat-herders/PM#18]
In order to track progress for the Istanbul hard fork, we should maintain an Istanbul Hardfork Tracker on the Ethereum Wiki, [here](https://en.ethereum.wiki/roadmap/istanbul/tracker). 

Past the following deadlines, from the [Istanbul Roadmap](https://en.ethereum.wiki/roadmap/istanbul), here is what we should expect in the tracker: 

> 2019-07-19 (Fri) soft deadline for major client implementations

**Suggestion**: Track implementation by linking specific "work tickets" related to EIPs (ex: JIRA tickets, Github issues, etc.) instead of simple checkmarks/tickboxes. 

> 2019-08-14 (Wed) projected date for testnet network upgrade (Ropsten, Görli, or ad-hoc testnet)

**Suggestion**: List client versions for Istanbul
**Suggestion**: Track "Istanbul-readiness" for testnets

> 2019-10-16 (Wed) projected date for mainnet upgrade (“Istanbul”)  

**Suggestion**: List client versions for Istanbul
**Suggestion**: Track "Istanbul readiness" for mainnet. 

In order for the tracker to be visible, it should probably be linked on the [AllCoreDevs Agenda](https://github.com/ethereum/pm/issues).

**Comment by bmann** [comment]
I think my PR closes this as editing the README https://github.com/ethereum-cat-herders/PM/pull/20 -- thanks Tim!
