### ISSUE TITLE
Bounty for documenting meeting notes for Ethereum Consensus Layer (Eth2) meeting 64

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/PM#180]
**Task** - Document notes for Ethereum Consensus Layer meeting 64

**Agenda** - https://github.com/ethereum/eth2.0-pm/issues/218

Guidelines & template - https://github.com/ethereum-cat-herders/PM/blob/master/Meeting_Notes_Template.md

Create a Pull Request [here](https://github.com/ethereum/eth2.0-pm/pulls) to submit the notes.

**Bounty** - 150 DAI

**Comment by DockBoss** [comment]
I will attempt the meeting notes.

**Comment by DockBoss** [comment]
@poojaranjan I just put in the pull request. Let me know if there is anything I can improve on.

**Comment by poojaranjan** [comment]
Thanks for your work. Bounty awarded.
