### ISSUE TITLE
EIP Status Banner

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/PM#182]
This project is described below:
<img width="1122" alt="Screen Shot 2021-06-02 at 9 23 05 PM" src="https://user-images.githubusercontent.com/26529820/120576634-b9162f80-c3e8-11eb-8034-67f8b651117b.png">

**Comment by alita-moore** [comment]
@poojaranjan can you please give me write access to this repo so I can manage these tickets?

**Comment by poojaranjan** [comment]
@alita-moore you have now permissions to read and clone this repository & also manage issues and pull requests. 
I suppose this work (EIP status Banner) has to be pushed to the EIP repo, and not merged here.

**Comment by alita-moore** [comment]
I will be tracking everything here

**Comment by poojaranjan** [comment]
@alita-moore on your request, the permission has been upgraded. You should now be able to read, clone, and push to this repository. Can also manage issues and pull requests.

**Comment by alita-moore** [comment]
Initial banner design:
<img width="904" alt="Screen Shot 2021-06-05 at 3 15 19 PM" src="https://user-images.githubusercontent.com/26529820/120904242-d9283780-c610-11eb-938a-846d87694741.png">

**Comment by alita-moore** [comment]
@poojaranjan I'm removing my tickets in favor of my personal fork to make it easier totrack issues as you mentioned; do you want me to move this one as well? https://github.com/alita-moore/PM/issues

**Comment by poojaranjan** [comment]
Closing the issue in favor of  #214 to open it for the community as discussed in the [EIPIP meeting 36](https://www.youtube.com/watch?v=wt7EB8MujgA) (at 44:44).
