### ISSUE TITLE
Document Process for Core EIP Proposal

### ISSUE THREAD

**Issue by timbeiko** [ethereum-cat-herders/PM#19]
In order for the community to know what is required to propose a Core EIP, we should document the process and "non-spec" requirements. Spec requirements can be found in [EIP-1](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1.md). 

The process documented should ideally cover everything from "I have an idea to an EIP" to "my EIP is live on mainnet". This includes, non-exhaustively: 
- Proposing an EIP
- Socializing an EIP / getting community support 
- The technical requirements for an EIP to be implemented (working code, test vectors, etc.)
- Client or financial support for implementation 
- etc.

**Comment by bmann** [comment]
Yes, something that is more human readable and is broader than the technical bits and covers CoreDev process would be good.

**Comment by timbeiko** [comment]
Thinking about this more, perhaps a better way to do this is to simply place a PR against https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1.md? Looking at what is already there, it seems like the socializing part is the least defined, along with the client/financial support.

**Comment by bmann** [comment]
All of the above ;)

I’d like to keep EIP-1 technically focused — while explaining a bunch more meta. 

I had said to EthHub that it might be good content for their site. 

We can use this repo and/or a HackMD to start this task. Could also be published as a page on the EIPs website.

**Comment by poojaranjan** [comment]
@timbeiko thanks for sharing, will update as we go.

**Comment by timbeiko** [comment]
I've created an outline of what this could look like in HackMD: https://hackmd.io/s/BJIB4Ofu4
A few questions before I go further:

1. Should we focus this on Core EIPs or any EIPs?
1. Is there anything that is missing from the process? I tried to model the outline on the EIP-1 format. 
1. How much/little should we reference EIP-1? Should the document assume someone has read + understood EIP-1, or should we assume no-prior knowledge?

**Comment by sneg55** [comment]
1. what's the difference between Core EIPs and other EIPs? 
3. I would assume no-prior knowledge

**Comment by timbeiko** [comment]
> what's the difference between Core EIPs and other EIPs?
"Core" is defined in the EIPS repo as the following:
> improvements requiring a consensus fork (e.g. EIP5, EIP101), as well as changes that are not necessarily consensus critical but may be relevant to “core dev” discussions (for example, EIP90, and the miner/node strategy changes 2, 3, and 4 of EIP86).
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1.md#eip-types

Basically, Core EIPs likely require a hard fork.

**Comment by bmann** [comment]
For reference to capture other discussions - here’s how README and EIP-1 conflict https://ethereum-magicians.org/t/eth1x-istanbul-prep-meeting/2396/9

**Comment by poojaranjan** [comment]
> I've created an outline of what this could look like in HackMD: https://hackmd.io/s/BJIB4Ofu4
> A few questions before I go further:
> 
> 1. Should we focus this on Core EIPs or any EIPs?
> 2. Is there anything that is missing from the process? I tried to model the outline on the EIP-1 format.
> 3. How much/little should we reference EIP-1? Should the document assume someone has read + understood EIP-1, or should we assume no-prior knowledge?


We may possibly add this in socialization, after introduction of draft EIP and / or before last call
- Introduce it (or Shout out for last call) on  gitter, reddit, and core dev call (possibly add it in agenda - new EIP / last call EIP )
- Blog post by the author for background, need and application of the EIP.
- Reach out to ECH or reviewers for review, when EIP is ready (if applied). ECH may coordinate with reviewers based on the interest / availability.

**Comment by timbeiko** [comment]
Small change to EIP1 proposed here: https://github.com/ethereum/EIPs/pull/1858

**Comment by timbeiko** [comment]
Linking this merged PR to EIP-1: https://github.com/ethereum/EIPs/pull/1896/files as well as a relevant EthMagicians thread: https://ethereum-magicians.org/t/definitions-of-governance-layers/3054

**Comment by poojaranjan** [comment]
Formal process of selection of EIPs for hardforks (Meta EIP#) proposed [here](https://github.com/poojaranjan/EIPs/blob/patch-1/EIPsForHardfork.md)

**Comment by timbeiko** [comment]
Closed my original PR in favor of https://github.com/ethereum/EIPs/pull/1991

**Comment by timbeiko** [comment]
And https://github.com/ethereum/EIPs/pull/1991 has just been merged 🎉! closing this issue.
