### ISSUE TITLE
Update Readme file of ethereum / pm

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/PM#191]
**Task**: Update the README file of ethereum/pm by adding Tim's tweet. 

**Estimated effort**: up to 5 hrs. 

Create a pull request [here](https://github.com/ethereum/pm/pulls).

**Comment by Avishek041180** [comment]
Pull request created - https://github.com/ethereum/pm/pull/338

**Comment by poojaranjan** [comment]
Task completed, payment disbursed.
