### ISSUE TITLE
Bounty for documenting notes (ACD meeting 116)

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/PM#213]
**Task** - Document notes for Ethereum ACD meeting 116

**Bounty** - 150 DAI

**Agenda** - https://github.com/ethereum/pm/issues/337

**Guidelines & template** - https://github.com/ethereum-cat-herders/PM/blob/master/Meeting_Notes_Template.md

**Submission timeline** - 3 days

Create a Pull Request to submit the notes [here](https://github.com/ethereum/pm/tree/master/All%20Core%20Devs%20Meetings)

(Earlier notes (for reference) - https://github.com/ethereum/pm/tree/master/All%20Core%20Devs%20Meetings.)

**Comment by golden-gringo** [comment]
Hello, I would be interested in helping document the notes for this meeting.

**Comment by poojaranjan** [comment]
@golden-gringo 
Thanks for responding. All details are added in the issue section. You may follow [earlier meeting notes](https://github.com/ethereum/pm/tree/master/All%20Core%20Devs%20Meetings) for reference. Let me know if you have any questions.

**Comment by golden-gringo** [comment]
Thank you!  I can begin working on this tonight, I will let you know when it is finished.

**Comment by golden-gringo** [comment]
I just submitted a pull request for the Meeting 116 notes, and the README file on the Ethereum GitHub. 
https://github.com/ethereum/pm/pulls

**Comment by poojaranjan** [comment]
Thanks for submitting the notes. A few formatting fixes are recommended. Please update the notes.
 If you're available on the Etherum Cat Herders Discord server, please DM me to learn how to claim the bounty.

**Comment by golden-gringo** [comment]
I updated the notes with the formatting fixes, let me know if there are any other fixes you would like me to make!

**Comment by poojaranjan** [comment]
Thanks for your work. Bounty is paid!
