### ISSUE TITLE
Add a warning label to all non-finalized EIPs 

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/PM#214]
**Task**: Add a warning statement to EIP pages at https://eips.ethereum.org/
Applicable to all _**non-finalized**_ EIPs 

![image](https://user-images.githubusercontent.com/29681685/124180372-1520b200-da82-11eb-9b0a-b83dff1d8534.png)

Ref: https://github.com/ethereum-cat-herders/PM/issues/182

If you're interested to work on this issue, please respond below. In case of questions or additional information leave a comment.

**Comment by feld** [comment]
I'm working on this, will link the pull request when it's ready.

**Comment by poojaranjan** [comment]
The pull request is approved and merged.

Appreciate your contribution, @feld !!
