### ISSUE TITLE
Bounty for documenting notes (Ethereum Cat Herders Meeting 62) 

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/PM#217]
**Task** - Document notes for Ethereum Cat Herders Meeting 62

**Bounty** - 50 DAI

**Agenda** - https://github.com/ethereum-cat-herders/PM/issues/212

**Guidelines & template** - https://github.com/ethereum-cat-herders/PM/blob/master/Meeting_Notes_Template.md

**Submission timeline** - 3 days

Create a Pull Request to submit the notes [here](https://github.com/ethereum/eth2.0-pm/tree/master/eth2.0-implementers-calls)

(Earlier notes (for reference) - https://github.com/ethereum-cat-herders/PM/tree/master/All%20Ethereum%20Cat%20Herder%20Meetings

**Comment by Avishek041180** [comment]
I will work on this note

**Comment by KenMan79** [comment]
I am submitting making the submission now

**Comment by KenMan79** [comment]
Had a personal issue that created a blocker

**Comment by Avishek041180** [comment]
PR - [ECH meeting 067](https://github.com/ethereum-cat-herders/PM/pull/219)

Please review and merge

**Comment by poojaranjan** [comment]
> I am submitting making the submission now
Had a personal issue that created a blocker

@KenMan79 Don't worry about it. I hope things are looking better at your end. 

As per the task, we've received the submission  (pull request) from @Avishek041180 within the submission timeline, so we're going to approve it. 

I am happy to have you scheduled for another meeting note if you're available.
