### ISSUE TITLE
Meeting #066

### ISSUE THREAD

**Issue by KenMan79** [ethereum-cat-herders/PM#228]
Meeting #225 PR Submitted

**Comment by poojaranjan** [comment]
@KenMan79 
The ECH meeting notes is expected to be submitted as a pull request for [this repo](https://github.com/ethereum-cat-herders/PM/tree/master/All%20Ethereum%20Cat%20Herder%20Meetings).

Sharing an earlier report for your [reference](https://github.com/ethereum-cat-herders/PM/blob/master/All%20Ethereum%20Cat%20Herder%20Meetings/Meeting%20064.md).

Please have the meeting notes for ECH meeting 66 submitted as a pull request and this issue can be closed. Thanks!

**Comment by poojaranjan** [comment]
Closing in favor of #229
