### ISSUE TITLE
JSON RPC Spec Writer required

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/PM#243]
### **Skills & experience required**
 * experience working with Ethereum JSON RPC.
 * experience writing comprehensive, yet precise specification documents
   See the Oasis Basleine standard as an example: https://github.com/eea-oasis/baseline-standard/blob/main/core/baseline-core-v1.0-psd01.md for example.

### **Responsibilities**
 * write Ethereum 1.0 JSON RPC API spec with one more junior writer.
  https://github.com/DockBoss/Execution-API-Spec/blob/main/spec/Ethereum_JSON_RPC_Spec.md
 * be able to launch an already prepared local testnet setup with 4 different Ethereum 1 clients.
 * work with limited supervision (15 minutes catch-up daily, one longer, 1h review session weekly).
 * be persistent, working regularly daily and delivering and reporting on progress daily.
 * be paid an hourly rate based on a B2B contract

If you're interested in this position, please reach me (Pooja Ranjan) on [ECH Discord](https://discord.io/ethereumcatherders).

**Comment by JEAlfonsoP** [comment]
Hi, I kindly would like to apply for this call.  
Thanks.

**Comment by poojaranjan** [comment]
This position is still open. If you're interested, please respond here.

**Comment by JEAlfonsoP** [comment]
Hi, Yes I am.

**Comment by poojaranjan** [comment]
No longer responded by team.
