### ISSUE TITLE
Bounty for documenting notes (Merge Community meeting #1)

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/PM#246]
**Task** - Document notes for Merge Community meeting #1

**Bounty** - 100 DAI

**Agenda** - https://github.com/ethereum/pm/issues/402

**Recording** - https://youtu.be/_kfS9jAUY6g

**Guidelines & template** - https://github.com/ethereum-cat-herders/PM/blob/master/Meeting_Notes_Template.md

**Submission timeline** - 3 days

Create a Pull Request to submit the notes [here](https://github.com/ethereum/pm/tree/master/Merge)

**Comment by stefan-wuest** [comment]
I would like to try and do it.
Has anyone got an attendance list so I can try to identify all speakers? Otherwise I just try and do my best from what's spoken and shown in the video.

**Comment by poojaranjan** [comment]
Great!
I am sorry the recording is not so good for the person documenting notes. You may add speaker 1, Speaker 2 instead of names. 

@trent_vanepps by any chance do we have a list of participants?

**Comment by stefan-wuest** [comment]
I used what I had/read/heard and tried to figure out as many names as possible. 👍🏼

**Comment by poojaranjan** [comment]
Thanks, @stefan-wuest!

I hope it will be reviewed by @trent_vanepps before getting merged but in the meantime, please follow the [document](https://github.com/ethereum-cat-herders/PM/blob/master/How_to_claim_bounty.md) to claim the bounty.

**Comment by poojaranjan** [comment]
@stefan-wuest 
I understand it was a difficult task in absence of the speaker's name, but you nicely tried to capture the content. It's great.

This was the first Merge community call and has already passed over 300 views. We hope to share the notes with the broader community to follow along. A neat representation is highly appreciated. 

I left a few suggestions on the overall document, it would be nice to see them incorporated.  

Once again, thank you for documenting the meeting.

**Comment by poojaranjan** [comment]
Task completed & bounty granted!
