### ISSUE TITLE
ECH Engineering (December 2021)

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/PM#259]
Contd. from [November 2021](https://github.com/ethereum-cat-herders/PM/issues/245)
- [ ] https://github.com/alita-moore/PM/issues/9
- [x] https://github.com/ethereum/EIP-Bot/issues/28
- [x] https://github.com/ethereum/EIP-Bot/issues/27
- [x] https://github.com/ethereum/EIP-Bot/issues/26
- [x] https://github.com/ethereum/EIP-Bot/issues/25

New:
- [ ] https://github.com/ethereum/EIP-Bot/issues/38
- [ ] https://github.com/ethereum/EIP-Bot/issues/34
- [ ] https://github.com/ethereum/EIP-Bot/issues/33
- [x] https://github.com/ethereum/EIP-Bot/issues/31 (@mryalamanchi)
- [ ] https://github.com/ethereum/EIP-Bot/issues/32
- [x] https://github.com/ethereum/EIP-Bot/issues/37 (@mryalamanchi)
- [x] https://github.com/ethereum/EIP-Bot/issues/30
- [x] https://github.com/ethereum/EIP-Bot/issues/29

**Comment by poojaranjan** [comment]
Closing in favor of #261
