### ISSUE TITLE
Take down progpowcarbonvote.com

### ISSUE THREAD

**Issue by lrettig** [ethereum-cat-herders/PM#26]
Take it down in two weeks, as decided on yesterday's call.

**Comment by lrettig** [comment]
I added a note to the site to this effect, and tweeted about it. Please help spread the word.

**Comment by lrettig** [comment]
I set the ending block number to 7504000 which should happen in 13-14 days:

https://github.com/lrettig/carbonvote/commit/90cf3aa6925e3f9da430d4ef81035dc7e89cbcfa

**Comment by timbeiko** [comment]
@lrettig should we close this?

**Comment by lrettig** [comment]
Yes, it's done. Data is archived here: https://github.com/lrettig/carbonvote/tree/final-data/data
