### ISSUE TITLE
Bounty for documenting notes (CL meeting 80)

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/PM#269]
**Task** - Document notes for CL meeting 80

**Bounty** - 150 DAI

**Agenda** - https://github.com/ethereum/pm/issues/458

**Guidelines & template** - https://github.com/ethereum-cat-herders/PM/blob/master/Meeting_Notes_Template.md

**Submission timeline** - 3 days

Create a Pull Request to submit the notes [here](https://github.com/ethereum/pm/tree/master/Consensus-Layer-Meetings)

(Earlier notes (for reference) - https://github.com/ethereum/pm/tree/master/Consensus-Layer-Meetings.

**Comment by Santhosh1692** [comment]
I will work on it.

**Comment by poojaranjan** [comment]
Thanks @Santhosh1692. Please share the Pull Request link, when available.

**Comment by poojaranjan** [comment]
bounty claimed.
