### ISSUE TITLE
Increase multisig security

### ISSUE THREAD

**Issue by lrettig** [ethereum-cat-herders/PM#28]
As discussed on today's call, the [multisig](https://etherscan.io/address/0x68085e7f88e90fa9247489c83fab30b177ebccb3#tokentxns) now contains > $14k USD as a result of the [progpow grant](https://gitcoin.co/grants/82/official-progpow-technical-audit-funding). Let's bump it up to a 2-of-3, and if possible, move the progpow funds to a separate multisig for accounting and accountability purposes.

**Comment by lrettig** [comment]
Tx sent to update required from one to two: https://etherscan.io/tx/0xffa55b38cfec634c366549c144c288bdde6b09448c065a35870ab988984d779f

**Comment by lrettig** [comment]
Done. @Souptacular @CPSTL we'll need to coordinate and have two of us approve each withdrawal now! FYI. Anyone can submit an initial tx, then someone else has to come along and confirm it.

**Comment by lrettig** [comment]
Leaving this open for now to discuss the second question: do we want to move the propgow funds to a different multisig?

**Comment by timbeiko** [comment]
@lrettig what is the status on this?

**Comment by CPSTL** [comment]
@timbeiko **Quick update**: we have not yet made a formal decision regarding the potential move of the ProgPow grant funds to a separate multisig. This is due to the fact that the CLR Round 2 had not closed & funds were not transferred over yet. However, CLR round 2 has now closed, so this can be decided on the next call or over chat!

**Comment by timbeiko** [comment]
Cool, let's discuss this on the next call. Thanks for the update! cc: @DBrettRobertson for the agenda.

**Comment by lrettig** [comment]
There's still some accounting to be done here. Cf https://github.com/gitcoinco/web/issues/4362

**Comment by Souptacular** [comment]
CLR funds have been added. Let's reopen this discussion.

**Comment by timbeiko** [comment]
Given that we've paid for the ProgPow audit and now have a 2 of 4 multisig, I'll close this issue for now. We can re-open more relevant new ones if needed.
