### ISSUE TITLE
Bounty for documenting notes (ACD meeting 139)

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/PM#291]
Task - Document notes for [ACD meeting 139](https://www.youtube.com/watch?v=5mMd-XHAv2Q)

Bounty - 150 DAI

Agenda - https://github.com/ethereum/pm/issues/528

Guidelines & template - https://github.com/ethereum-cat-herders/PM/blob/master/Meeting_Notes_Template.md

Submission timeline - 3 days

Create a Pull Request to submit the notes [here](https://github.com/ethereum/pm/tree/master/AllCoreDevs-Meetings)

Respond to this issue if you would like to work on this task.

**Comment by Santhosh1692** [comment]
I will work on it

**Comment by Santhosh1692** [comment]
It is complete https://github.com/ethereum/pm/pull/542

**Comment by poojaranjan** [comment]
thanks!
