### ISSUE TITLE
Bounty for documenting notes (Merge Community meeting 4)

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/PM#292]
Task - Document notes for [Merge meeting #4](https://youtu.be/qG-A5i6x6N8)

Bounty - 100 DAI

Agenda - https://github.com/ethereum/pm/issues/532

Guidelines & template - https://github.com/ethereum-cat-herders/PM/blob/master/Meeting_Notes_Template.md

Submission timeline - 3 days

Create a Pull Request to submit the notes [here](https://github.com/ethereum/pm/tree/master/Merge)

Respond to this issue if you would like to work on this task.

**Comment by arredr2** [comment]
I'm on it!

**Comment by poojaranjan** [comment]
If this is completed, please share the pull request. 
Also, DM me (Pooja Ranjan) on ECH Discord and I will share the process tp claim bounty for this task.

**Comment by arredr2** [comment]
This is now completed. https://github.com/ethereum/pm/pull/563
