### ISSUE TITLE
Looking for a frontend dev for L2E

### ISSUE THREAD

**Issue by geovgy** [ethereum-cat-herders/PM#294]
We are looking for another dev willing to contribute to our ECH learn-2-earn app. The reason is to make this a project with multiple contributors that can improve and maintain it. At the time of writing this, we are close to finishing the first version and will be launching it soon. But there are some new features and such we expect to include in the next versions in which new contributors are highly encouraged to take on.

Repo: https://github.com/ethereum-cat-herders/L2E

Tech stack:
- NextJS
- ChakraUI
- Moralis

If interested or have questions, please either comment on this issue or reach out in the ECH discord. Thank you.

**Comment by poojaranjan** [comment]
Position filled.
