### ISSUE TITLE
Delete www repo

### ISSUE THREAD

**Issue by bmann** [ethereum-cat-herders/PM#30]
I think the site is being generated from here: https://github.com/ethereum-cat-herders/ethereum-cat-herders.github.io

Although the www repo is ALSO being generated, so it is duplicated here http://www.ethereumcatherders.com/www/

So, I think the WWW repo can be deleted.

**Comment by lrettig** [comment]
@HugoSanchez is this yours?

**Comment by HugoSanchez** [comment]
Hey @adamschmideg do you know which one is the one to be deleted?

**Comment by adamschmideg** [comment]
bmann is right, https://github.com/ethereum-cat-herders/www can be deleted

**Comment by HugoSanchez** [comment]
Done, thanks everyone!

**Comment by poojaranjan** [comment]
Issue resolved.
