### ISSUE TITLE
Figure out next timing / location of in-person meeting

### ISSUE THREAD

**Issue by bmann** [ethereum-cat-herders/PM#32]
@timbeiko you were the one discussing this with me so I’m tagging you again ;)

I would suggest this get done in North America. 

Do we need one before the October hardfork? What timelines should it sync up with?

**Comment by timbeiko** [comment]
It may be good to bring this up at the Berlin meetings. I personally feel that these meetings are most helpful at the "figuring out what EIPs to include" stage rather than the "coordination of the actual hard fork" stage, but others may disagree. 

To me, the next meeting would depend on when Istanbul and the HF after that happen. It's hard to plan ahead when there is still uncertainty about whether or not the HF schedule will change.

**Comment by bmann** [comment]
I think Istanbul timing is set until someone steps up to propose a post Istanbul timing. 

Yes we will discuss in Berlin. 

I’d love to announce location and date by the time Berlin is over.

**Comment by meknab** [comment]
if there is an appetite for holding it in nyc or seattle I'd be happy to coordinate administratively

**Comment by lrettig** [comment]
If we're aiming for network upgrades roughly every six months, then we may want to meet roughly every six months. That puts us at October though, which is very close to Devcon.

**Comment by timbeiko** [comment]
FWIW, after informally asking a few PegaSys people, roughly 1x/quarter seems right. Devcon -> Stanford Meetings -> Berlin -> Devcon is more or less on that schedule.

**Comment by bmann** [comment]
I think aiming for once per quarter is a good idea. Also means you can easily “miss” some of them. 

Moving continents can also be a goal. 

I do want to do at least one fully “virtual conference” too. 

So early July or early August? And one we have @meknab volunteering to help be an on site organizer in Seattle or NYC. We’ll make a call for organizers & hosts here in Berlin and get feedback on times and places.

**Comment by bmann** [comment]
Here's the discussion / voting https://ethereum-magicians.org/t/coredevs-eth1x-istanbul-meeting-july-poll-feedback/3197

**Comment by timbeiko** [comment]
@bmann as I understand it, this meting probably won't happen, correct? 

If so, is it safe to say there won't be an in-person until possibly devcon? I've seen a thread on EthMagicians about organizing a [Council of Osaka](https://ethereum-magicians.org/t/council-of-osaka-date-and-place/3367). Perhaps it makes sense to merge this with ECH and AllCoreDevs.

**Comment by lrettig** [comment]
> @bmann as I understand it, this meting probably won't happen, correct?

This is my understanding as well.

**Comment by bmann** [comment]
No idea. I am stepping back from organizing anything to do with Core. I said I’d support @shemnon in doing an online meeting in July https://ethereum-magicians.org/t/coredev-july-online-meeting/3333

This can be closed, and a new issue or thread should be started on other plans to meet.
