### ISSUE TITLE
forum.ethereum.org - abandoned community forum

### ISSUE THREAD

**Issue by sneg55** [ethereum-cat-herders/PM#33]
Do we know who is in charge with that forum? It looks abandoned and also there are questionable ads of miners chassis right in the forum header. 

@bmann  said on ECH gitter that it's probably should be taken down.

**Comment by lrettig** [comment]
CC @Souptacular @jpitts

**Comment by sneg55** [comment]
Proposal: 301-redirect old domain to https://community.ethhub.io

**Comment by bmann** [comment]
HTTrack https://www.httrack.com/ or similar can be used to archive, can check into a GitHub repo and host via GHPages.

**Comment by lrettig** [comment]
Relevant tweeter thread: https://twitter.com/hudsonjameson/status/1132121595705778179?s=20

**Comment by timbeiko** [comment]
@jpitts @Souptacular do you think archiving this make sense? This is obviously an EF decision. If not, should we just close this issue?

**Comment by Souptacular** [comment]
I would love to archive it. When I get time I will try HTTrack as @bmann suggested.

**Comment by DBrettRobertson** [comment]
This has been closed on advice from @Souptacular that this is now being looked into and managed by the Ethereum Foundation.
