### ISSUE TITLE
Make this repo the default place to file issues

### ISSUE THREAD

**Issue by bmann** [ethereum-cat-herders/PM#34]
If someone in the Ethereum community doesn’t know where to file an issue — we should invite them to do it here. 

In general, except for very project / repo specific issues, it would be helpful to have all ECH projects have issues here. We can split up when there is more volume. 

Also, let’s use Projects! And labels!

**Comment by lrettig** [comment]
SGTM. We should add documentation to this effect to the repo's README.

**Comment by timbeiko** [comment]
I opened https://github.com/ethereum-cat-herders/PM/pull/73 . @lrettig can you +1?

**Comment by timbeiko** [comment]
Fixed by https://github.com/ethereum-cat-herders/PM/pull/73?
