### ISSUE TITLE
Bug: blog.ethereum.org LinkedIn icon in footer links to a random user

### ISSUE THREAD

**Issue by bmann** [ethereum-cat-herders/PM#35]
The footer of https://blog.ethereum.org has a LinkedIn icon that links to https://linkedin.com/in/ethereum -- this is a person, not an 

I couldn't find the source of this blog, otherwise I would have made a pull request to help fix it.

If we're going to link to LinkedIn at all, people probably meant to link to https://www.linkedin.com/company/ethereum/ -- which should be labelled as Ethereum Foundation.

**Comment by lrettig** [comment]
Ping @Souptacular @jpitts - any chance you guys could fix this?

**Comment by bmann** [comment]
Yay! The Link was removed! Still have no idea who has control over the repo that runs the blog.
