### ISSUE TITLE
FE Dev and Designer needed for new project

### ISSUE THREAD

**Issue by geovgy** [ethereum-cat-herders/PM#357]
We are beginning a new project for ECH and looking for a designer and another frontend developer to help build the MVP.

The project is a directory of ERCs that provides details and resources such as videos, packages and examples of the ERC implemented in real projects. It is to serve as a resource for hackers and learners.

We are currently in the planning stage and ready to build. Help us with the design and development. Let's BUIDL together!

If you are interested, please reach out to either me (georgeh) or Pooja in the ECH discord. Or leave a comment below.

**Comment by poojaranjan** [comment]
the position is closed!
