### ISSUE TITLE
Give Boris access to this repo

### ISSUE THREAD

**Issue by bmann** [ethereum-cat-herders/PM#36]
@DBrettRobertson said that he would see about granting me access to this repo.

Please let me know if this is possible and/or who has control over this repo and can get it done.

**Comment by lrettig** [comment]
Invited you to the ECH github org, @bmann - that should do the trick, let us know if it worked.

**Comment by bmann** [comment]
@lrettig member of the org, thank you! Still need admin / maintainer access to this PM repo.

Started by making a project board: https://github.com/orgs/ethereum-cat-herders/projects/2

**Comment by bmann** [comment]
Woot. Done. Thanks Lane!
