### ISSUE TITLE
State improvements question from Vitalik

### ISSUE THREAD

**Issue by bmann** [ethereum-cat-herders/PM#40]
> Q1  to Alexey: is his prototype using hexary trees or binary?

> Q2 there's two levels of "non-naiveness": the first level is that if two merkle branches share the same node you merge the node, the second level is that if you get all children of a node you don't need to include the parent of the node
> I'm guessing it's just the first level that gives the 3x improvement, correct?
> If it's hexary, I suspect the second level would give a tiny gain

For @AlexeyAkhunov to answer.

**Comment by AlexeyAkhunov** [comment]
Answers:
Q1: Prototype is using hexary trees
Q2: Yes, I think your intuition is right, although I did not explicitely try to measure it, because i just implemented multi-proof (without knowing they are called multiproof), because it just seemed the only correct way of doing it

**Comment by lrettig** [comment]
Thanks @AlexeyAkhunov! CC @vbuterin, and closing unless something is still outstanding.
