### ISSUE TITLE
Consensus testing with Retesteth

### ISSUE THREAD

**Issue by bmann** [ethereum-cat-herders/PM#43]
Capture action items of RPC changes needed, client changes, and identifying hard forks

Tie into larger testing initiatives

**Comment by bmann** [comment]
Also: coordinate with Zack from Whiteblock

**Comment by timbeiko** [comment]
@bmann has there been an update here?

**Comment by lrettig** [comment]
CC @winsvega @ledgerwatch

**Comment by bmann** [comment]
This was me posting issues from CoreDevsBerlin. The Testing Working group is here https://ethereum-magicians.org/t/ethereum-1-x-testing-working-group/3268

Let’s consider this closed. 

@lrettig stop randomly tagging people. The goal is to either assign an issue or close it.
