### ISSUE TITLE
[State Rent option 1] Stateful Track - Testing the ideal statefulness differential 

### ISSUE THREAD

**Issue by MadeofTin** [ethereum-cat-herders/PM#45]
There is a possibility that looking at the difference between the previous state can be used to reduce state size. There is also a possible there is an optimal n-states to consider. This can be discovered through testing.

**Comment by timbeiko** [comment]
@MadeofTin is this issue (and related ones) still relevant now that EIPs have been filed for Istanbul? 
Specifically:
* https://github.com/ethereum-cat-herders/PM/issues/46
* https://github.com/ethereum-cat-herders/PM/issues/47

Thanks!

**Comment by timbeiko** [comment]
Closing due to the work on State Fees/Rent being paused in favor of Stateless Clients. See [this](https://medium.com/@akhounov/on-the-state-rent-and-pivot-to-stateless-ethereum-ab4d967ff630) for details.
