### ISSUE TITLE
[State Rent option 2] Stateless track - Needs help with Compressed STARKs in Prime Fields

### ISSUE THREAD

**Issue by MadeofTin** [ethereum-cat-herders/PM#46]
Current STARKS use  2^n Galois fields. These are efficient for addition operations however, this is not ideal for the state proofs being considered to reduce state size. Prime fields are a much better candidate, but currently there is no existing implementation. This is something Alexey needs help to proceed.

**Comment by timbeiko** [comment]
Closing due to the work on State Fees/Rent being paused in favor of Stateless Clients. See this for details.
