### ISSUE TITLE
[State-Rent] Evaluate if Linear Storage Backed is correct.

### ISSUE THREAD

**Issue by MadeofTin** [ethereum-cat-herders/PM#47]
Notes:
 * Could be better for the EWASM implementation as Linear Storage is part of that spec. Increasing operability with existing libraries. Example using a Red-Black Tree implementation compiled from another language using linear storage.
 * Most developers already think in Arrays over Maps. Unnecessary internal complexity arises from implementations where Devs use an array because traditionally arrays are simpler where currently the inverse is true.

**Comment by lrettig** [comment]
This is being tracked from the Ewasm side here: https://github.com/ewasm/design/issues/188

**Comment by timbeiko** [comment]
@lrettig should we close this as a duplicate of your ewasm issue?

**Comment by lrettig** [comment]
👍
