### ISSUE TITLE
Create a carbonvote for progpow

### ISSUE THREAD

**Issue by lrettig** [ethereum-cat-herders/PM#5]
An anonymous community member has offered a bounty on this task (see Gitcoin bounty info, below). Here are the requirements:

1. Buy a domain name such as "Progpowcarbonvote.com"
1. Set up a carbon vote (https://github.com/EthFans/carbonvote) on the domain with the question, "Should Ethereum change the proof of work algorithm to ProgPoW?" The only possible answers should be "yes" or "no".

Task should be completed by 23:59pm tomorrow (Feb. 9) Pacific Time.

**Comment by salanki** [comment]
It seems as the Carbonvote is unreachable.

```
$ curl -v https://progpowcarbonvote.com
* Rebuilt URL to: https://progpowcarbonvote.com/
*   Trying 3.89.77.28...
* TCP_NODELAY set
* Connection failed
* connect to 3.89.77.28 port 443 failed: Operation timed out
* Failed to connect to progpowcarbonvote.com port 443: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to progpowcarbonvote.com port 443: Operation timed out
```

**Comment by lrettig** [comment]
I don't think it was ever set up via SSL/TLS.
