### ISSUE TITLE
Meta EIP for ewasm

### ISSUE THREAD

**Issue by MadeofTin** [ethereum-cat-herders/PM#52]

**Comment by timbeiko** [comment]
@lrettig any update here? Is this still relevant? Thanks!

**Comment by lrettig** [comment]
Ewasm folks especially @axic had a hand in several of the [Istanbul EIPs](https://eips.ethereum.org/EIPS/eip-1679) but AFAIK we're not targeting any Ewasm specific EIPs for Istanbul. Closing.
