### ISSUE TITLE
Versioning of the VM - does it make it into Istanbul

### ISSUE THREAD

**Issue by MadeofTin** [ethereum-cat-herders/PM#53]

**Comment by lrettig** [comment]
There are several outstanding EIPs covering different versions of this. See also https://ethereum-magicians.org/t/evm-instruction-set-versioning/2286. @sorpaas did a presentation on this topic in Berlin a few days ago, we should link to his slides or video of his talk here.

**Comment by sorpaas** [comment]
The slides are here ([source](https://git.that.world/talks/20190417-account-versioning.git/), [direct download link](https://git.that.world/talks/20190417-account-versioning.git/plain/presentation.pdf)). EIPs covered in the talk includes:

* EIP-1702: https://eips.ethereum.org/EIPS/eip-1702
* EIP-1707: https://github.com/ethereum/EIPs/pull/1707 (also [Issue #154](https://github.com/ethereum/EIPs/issues/154))
* EIP-1712: https://github.com/ethereum/EIPs/pull/1712
* EIP-1891: https://github.com/ethereum/EIPs/pull/1891

It feels like currently the most promising one is EIP-1702 (including the "Alternative Design" section). 

[The one in Ethereum Magicians](https://ethereum-magicians.org/t/evm-instruction-set-versioning/2286) looks to me like a variation of EIP-1707 / Issue `#154` thus suffers the same problem (i.e. we'll either break "minor" backward compatibility continuously, or break backward compatibility for one last time by combining it with EIP-1712).

**Comment by lrettig** [comment]
Thanks Wei! This is amazing!

**Comment by lrettig** [comment]
@sorpaas is there a reason you haven't submitted any of these for Istanbul yet? What would that take? CC @axic @cdetrio

**Comment by cdetrio** [comment]
What do you mean by "submit for Istanbul"?

**Comment by lrettig** [comment]
It's not on the list of EIPs proposed for Istanbul: https://github.com/ethereum-cat-herders/PM/blob/master/Hard%20Fork%20Planning%20and%20Coordination/IstanbulHFEIPs.md or https://en.ethereum.wiki/roadmap/istanbul

**Comment by bmann** [comment]
Since we have an update to 233, PRs to 1679 would be the next step. Everything else is nice to have for informative / tracking.

I’ll update the wiki to make that clear.

**Comment by sorpaas** [comment]
@lrettig @bmann I created PR https://github.com/ethereum-cat-herders/PM/pull/63. Let me know if there's anything else I need to do at this moment.

**Comment by bmann** [comment]
@sorpaas sorry but it needs to be PRd into 1679 https://eips.ethereum.org/EIPS/eip-1679

@lrettig this list in ECH is causing confusion. I think tracking issues on the Istanbul GitHub project would be super useful but a Markdown file that isn’t in sync with 1679 is wasted effort.

**Comment by bmann** [comment]
@lrettig @poojaranjan have a look at the project board here https://github.com/orgs/ethereum-cat-herders/projects/2 -- ideally this is something ECH can review on a weekly basis and keep things moving.

**Comment by bmann** [comment]
OK, marking this as closed.
