### ISSUE TITLE
Ewasm spec in a digestible format

### ISSUE THREAD

**Issue by MadeofTin** [ethereum-cat-herders/PM#55]

**Comment by bmann** [comment]
@MadeofTin I labeled this as State Fees for now -- do you remember if it was for that or for something else? Assigning to you for now to update.

**Comment by MadeofTin** [comment]
It was for EWASM. Came up during the EWASM - EVM discussion.

**Comment by lrettig** [comment]
We discussed this on the Ewasm team call today. I'll assign to myself.

**Comment by bmann** [comment]
@lrettig the other thing is publish a roadmap. Can you / @axic / @cdetrio figure out who owns that and file a tracking issue.

**Comment by timbeiko** [comment]
@lrettig is this still relevant? If not, do you have a link to the digestible spec we can share here before closing? Thanks!

**Comment by lrettig** [comment]
This is the de facto spec for Ewasm for Eth 1.x (as implemented on the Ewasm testnet): https://github.com/ewasm/design/blob/master/eth_interface.md. But things are very up in the air at the moment as work is transitioning to the Eth 2 execution engine. I don't think we'll see another spec here for quite some time. Not sure if @MadeofTin was envisioning something else here. I'm going to close this as I don't think there's an immediate task here.
