### ISSUE TITLE
Benchmarking opcodes for better gas prices

### ISSUE THREAD

**Issue by MadeofTin** [ethereum-cat-herders/PM#56]

**Comment by timbeiko** [comment]
@MadeofTin do you know of anywhere we can point to for more details? thanks!

**Comment by lrettig** [comment]
Ewasm is working on this in https://github.com/ewasm/design/issues/32 (as well as a few related issues)

**Comment by timbeiko** [comment]
Thanks for the update @lrettig. Closing for now as people can refer to your link if they want to follow the work. Feel free to re-open if you see a need to.

**Comment by lrettig** [comment]
Strictly speaking, based on the label, I think this task was about the EVM Evolution project, not Ewasm, but that project doesn't seem to be getting cycles at the moment so let's keep this closed.
