### ISSUE TITLE
Propose cheesy Hard Fork timing

### ISSUE THREAD

**Issue by bmann** [ethereum-cat-herders/PM#59]
Danno @shemnon wrote up a suggested cadence of hard forks in the EthMagicians thread https://ethereum-magicians.org/t/more-frequent-smaller-hardforks-vs-less-frequent-larger-ones/2929/28?u=boris

It showcases 4 months vs 6 months.

Danno, can you add this to agenda for an upcoming Core Devs Call and be a point of contact for this?

**Comment by lrettig** [comment]
It was proposed here: https://github.com/ethereum/pm/issues/95#issuecomment-486397389
