### ISSUE TITLE
Split livestream videos into individual videos per talk

### ISSUE THREAD

**Issue by bmann** [ethereum-cat-herders/PM#61]
The CoreDevsBerlin wiki page is a summary of all the discussions https://en.ethereum.wiki/eth1/coredevsberlin

There are links to the full day livestream on the Ethereum YouTube, with timecode links to the individual talks.

It can be useful to have separate videos for each talk. Looking for someone to download the source files and then turn them into separate files for each talk.

EVM Evolution already done https://www.youtube.com/watch?v=qck2KBqT14o&t=8s

Source files:
* https://drive.google.com/open?id=10HzA1DrD5vO3xWMaXD6tiMOK8PLuweOC
* https://drive.google.com/open?id=10JDzCqGkPmfhvvXuPNnpIRJrtB2eYmtn
* https://drive.google.com/open?id=10JSAOvay0yLRREV3A82owKY1fkGqbcKC

**Comment by lrettig** [comment]
I think @Souptacular is working on this isn't he?

**Comment by bmann** [comment]
Yes uncut is done. I cut out EVM evolution — calling for help here is someone from community wants to do this. 

Just leave as help wanted - would be good to broadcast that label every once in a while to get a flow of new volunteers.

**Comment by timbeiko** [comment]
@bmann is there any work left to do on this?

**Comment by bmann** [comment]
No has bothered to cut the talks into individual files. Time codes are linked on the wiki. Assume this is stale and no one cares / sees value. Closing!
