### ISSUE TITLE
EIP1829 support for 512bit or just 256bit?

### ISSUE THREAD

**Issue by bmann** [ethereum-cat-herders/PM#62]
From ACD https://github.com/ethereum/pm/issues/95, from @vbuterin

does the precompile for generic EC support 512 bit moduli?  or just 256? 

If 256 that makes it less interesting because it can't support bls 12 381 and hence eth2 light clients

**Comment by gumb0** [comment]
It says

> 256-bit modulus. This EIP is for field moduli less than 2^{256}. This covers many of the popular curves while still having all parameters fit in a single EVM word.
> 
> TODO: Consider a double-word version. 512 bits would cover all known curves except E-521. In particular it will cover the NIST P-384 curve used by the Estonian e-Identity and the BLS12-381 curve used by ZCash Sappling.

**Comment by bmann** [comment]
I’m going to consider this closed, track EIP1829 for further progress.
