### ISSUE TITLE
Champion wanted: EIP 689 Address Collision of Contract Address Causes Exceptional Halt

### ISSUE THREAD

**Issue by bmann** [ethereum-cat-herders/PM#66]
From [ACD 60](https://github.com/ethereum/pm/issues/95), @axic brought up https://eips.ethereum.org/EIPS/eip-689 -- seems useful, needs someone to drive it.

**Comment by MadeofTin** [comment]
I did some research. This is already implemented in the client codes. What is missing is testing and an update to the yellow paper so it is explicit in the spec.

Neither of these require a hard fork, but still worth pursuing. I am working with dimitry on the requirements for writing the tests.

**Comment by lrettig** [comment]
@MadeofTin thanks for looking into this - it would be helpful to include links into a couple of the clients here to see where/how it's implemented.

**Comment by timbeiko** [comment]
@MadeofTin friendly ping :-)
