### ISSUE TITLE
Shared Google account for herders

### ISSUE THREAD

**Issue by lrettig** [ethereum-cat-herders/PM#68]
@DBrettRobertson already set this up (ethereumcatherders@gmail.com). We'll communicate access information via a separate channel. Right now it's just used for access to the Zoom Pro account. We can also share the calendar with all of the herders.

**Comment by timbeiko** [comment]
@lrettig do we need to keep this issue open? How should herders get access to the account? Thanks!

**Comment by lrettig** [comment]
Let's discuss on the next meeting (#75)

**Comment by DBrettRobertson** [comment]
Close issue - @lrettig and @DBrettRobertson can grant access to the account as required.
