### ISSUE TITLE
EIP-1283 and EIP-1706 for Istanbul

### ISSUE THREAD

**Issue by sorpaas** [ethereum-cat-herders/PM#69]
I heard there were still interests in getting EIP-1283 (plus some fixes) into mainnet, so I'm thinking about getting EIP-1283 and EIP-1706 into Istanbul.

**Comment by timbeiko** [comment]
@sorpaas now that this conversation seems to have moved to AllCoreDevs, do you think it makes sense to close this issue? Thanks!

**Comment by sorpaas** [comment]
Yeah sure!
