### ISSUE TITLE
Write a road to Istanbul, proposed EIPs post

### ISSUE THREAD

**Issue by bmann** [ethereum-cat-herders/PM#70]
As suggested by Holger Drewes in ACD Gitter, write a blog post on the Ethereum blog about the road to Istanbul — including proposed EIPs in 1679 and what it will take to get them all the way to Accepted and then Included in the hard fork.

**Comment by holgerd77** [comment]
Will include me here for further notice, also @souptacular.

**Comment by holgerd77** [comment]
My time is hyper-limited due to baby duties atm, but if this comes to fruition I can propose to do the inner to-the-metal EIP summary part, since I have to approach this anyhow for EthereumJS planning.

**Comment by bmann** [comment]
I’ll probably get to this and we can post to EthMagicians and it can be cross posted to the blog of we can get permission. 

One other thing I want to include and will likely keep up to date in the wiki is Working Group and/or individual champion point of contacts for each EIP.

**Comment by holgerd77** [comment]
Very cool! :+1: :smile:

**Comment by timbeiko** [comment]
@bmann happy to review or assist with this as needed. Feel free to ping me if you need anything.

**Comment by timbeiko** [comment]
@bmann did this ever happen? It seems somewhat captured by https://en.ethereum.wiki/roadmap/istanbul but it may be valuable to have in a more digestible format.
