### ISSUE TITLE
Eth2 Phase 2 Implementors' Call

### ISSUE THREAD

**Issue by lrettig** [ethereum-cat-herders/PM#72]
Hello,

@villanuevawill, myself and a few others would like to set up a monthly call for Eth2 Phase 2 implementors. It should be recorded and ideally livestreamed. We also need a public Telegram and/or Gitter channel for participants to communicate. Is this something we could help set up?

Thanks!

**Comment by timbeiko** [comment]
@lrettig @villanuevawill any updates on this?

**Comment by lrettig** [comment]
I'm no longer directly involved in this initiative. Thanks for following up, @timbeiko. Okay w me to close this issue.
