### ISSUE TITLE
Redirect old Ethereum wiki to new eth.wiki

### ISSUE THREAD

**Issue by bmann** [ethereum-cat-herders/PM#77]
Looks like @virgil updated the Ethereum wiki to run WikiJS 2 — which is great, see https://eth.wiki

I would request installing redirects on the old site https://en.ethereum.wiki to the new site, which will prevent tons of broken links. 

I believe NameCheap does free path redirects with DNS hosting. Let me know if I can assist.

**Comment by Souptacular** [comment]
I pinged @virgil about this.

**Comment by virgil** [comment]
Fixed.

**Comment by lrettig** [comment]
I see this now at the old URL:
![image](https://user-images.githubusercontent.com/3316532/59917852-59086780-9423-11e9-85ea-4656673131a1.png)

**Comment by virgil** [comment]
Yeah making those redirections work with SSL, for free, was nontrivial.  So I satisfied myself to simply having http work.  If the consensus is that we *really* want SSL redirections to work, I can find a way to do it.

**Comment by virgil** [comment]
Solved.

**Comment by lrettig** [comment]
Great thanks! Closing

**Comment by bmann** [comment]
This is not solved. @virgil can you please do path redirects? E.g. /roadmap/Istanbul redirects to the new page rather than the home page. 

Google domains does this for free. 

Let me know if you need help and/or transfer the domain to me and I’ll do it.

**Comment by virgil** [comment]
fixed.

**Comment by bmann** [comment]
Confirmed. Thanks @virgil!
