### ISSUE TITLE
Ethereum Cat Herders Call #15 - Agenda

### ISSUE THREAD

**Issue by DBrettRobertson** [ethereum-cat-herders/PM#80]
## Date and Time

Proposed time is 14:00 UTC on Tuesday, July 9th, 2019.

## Location 

Zoom: The link has been sent to attendees.
YouTube Livestream Link: TBA

## Agenda 

1. Update on ProgPow Audit
1. Hard Fork Coordination Update
1. Updates on the action items from Constantinople post-mortem
1. Funding/accounting/multisig
4.1 Update on account of ECH funding.
1. [DevCon Workshop Proposal](https://docs.google.com/document/d/1IGPx2xGcdChUPdExWKCC5ejr8X_wIxf_NeIHmtpB5mQ/edit#)
1. Any Other Business
1. Review of outstanding action items from Meeting 12

- ACTION 9.1: Hudson to work with Charles on making a post about ProgPoW audit.
- ACTION 9.4: Multisig keyolders to work on seperating the funds.
- ACTION 11.1: Cat Herders to review the [document](https://github.com/poojaranjan/ECH-PM/blob/master/Constantinople%20Postmortem%20Report/EmergencyCommTemplate.md) created by Pooja.
- ACTION 12.2: Continue to look into discrepency with Gitcoin Bounty amount. 
- ACTION 14.1: Double check the funding from Gitcoin.
- ACTION 14.2: Follow up with Hudson and resolve to decide what to do with the ProgPoW funds.
- ACTION 14.3: William to work with Lane on an intiative to perform an account of the current ECH funding.
- ACTION 14.4: Create a vote within the Ethereum Cat Herders DAO to decide if the 100 DAI is appropriate for Ethereum Core Dev and Ethereum 2.0 Notes and 50 DAI for ECH notes.
- ACTION 14.5: Engage with Hudson regarding the requirements for streaming of ECH calls.
- ACTION 14.6:Tim will raise a PR to link the Live streaming document within the Cat Herders repo.
- ACTION 14.7: Lane to create a seperate Gnosis wallet to assist with registering for reputation within the dxDAO.

**Comment by timbeiko** [comment]
@DBrettRobertson you can remove the Devcon Workshop agenda item, as the deadline will have passed before the next call.

**Comment by timbeiko** [comment]
Closing in favor of https://github.com/ethereum-cat-herders/PM/issues/83
