### ISSUE TITLE
Cannot access http://www.devcon.org

### ISSUE THREAD

**Issue by lrettig** [ethereum-cat-herders/PM#81]
I noticed that, while http://devcon.org (without www, with or without https) works, if you add the www, it doesn't.

@Souptacular @jpitts is this something one of you could address?

Thanks

**Comment by lookfirst** [comment]
Someone forgot the A record for www.

```
$ host devcon.org
devcon.org has address 35.167.60.117
devcon.org mail is handled by 20 aspmx2.migadu.com.
devcon.org mail is handled by 10 aspmx1.migadu.com.
$ host www.devcon.org
$
```

**Comment by virgil** [comment]
Fixed.

**Comment by timbeiko** [comment]
Thanks!
