### ISSUE TITLE
Ethereum Car Herders Meeting #17 - Agenda

### ISSUE THREAD

**Issue by timbeiko** [ethereum-cat-herders/PM#84]
## Date and Time

Tuesday, 13 August 2019 [14:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-ny-new-york-city/2pm) 

## Location 

Zoom: The link has been sent to attendees.
YouTube Recording Link: **TBA**

## Agenda 

1. Hard Fork Coordination Update
1. Updates on the action items from Constantinople post-mortem
1. Funding/accounting/multisig
    1. Update on account of [ECH funding](https://github.com/ethereum-cat-herders/funding/issues)
1. Any Other Business
1. Review of outstanding action items
    - ACTION 16.1: Lane and Brent to investigate the ProgPow Funding / ECH Gitcoin Discrepancy

**Comment by poojaranjan** [comment]
Adding link to agenda item 
3. Funding/accounting/multisig
   i. Update on account of [ECH funding](https://github.com/ethereum-cat-herders/funding/issues)

**Comment by DBrettRobertson** [comment]
Meeting Complete.
