### ISSUE TITLE
ethereum.org has incorrect DNS settings

### ISSUE THREAD

**Issue by bmann** [ethereum-cat-herders/PM#85]
The root domain does not redirect to www. Visiting https://ethereum.org or http://ethereum.org results in site not found. 

The actual website is at https://www.ethereum.org

Fix: set DNS to redirect the root. Depends on the DNS registrar how to do this. 

What happened? Who changed it? How can we  make this sure it doesn’t happen again?

Cc @jpitts @souptacular

**Comment by lrettig** [comment]
https://ethereum.org and http://ethereum.org work for me right now.

**Comment by bmann** [comment]
@lrettig got fixed in the meantime. Sure would like to know what happened and be confident that it won’t happen again.
