### ISSUE TITLE
Agenda: Ethereum Cat Herders Meeting #18

### ISSUE THREAD

**Issue by DBrettRobertson** [ethereum-cat-herders/PM#86]
## Date and Time

Tuesday, 27 August 2019 [14:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-ny-new-york-city/2pm) 

## Location 

Zoom: The link has been sent to attendees.
YouTube Recording Link: **TBA**

## Agenda 

1. EEA Devcon Workshop
1. Hard Fork Coordination Update
1. Updates on the action items from Constantinople post-mortem
1. Funding/accounting/multisig
    1. Update on Gitcoin discrepancy
    1. Update on ECH Notes funding [ECH funding](https://github.com/ethereum-cat-herders/funding/issues)
1. Helping to organize the [pre-devcon EthMagicians council](https://ethereum-magicians.org/t/council-of-osaka-date-and-place/3367/16).
1. Any Other Business
1. Review of outstanding action items

**Comment by timbeiko** [comment]
@DBrettRobertson could we add an action item about the EEA's devcon workshop? They will be on the call to discuss. Thanks!

**Comment by DBrettRobertson** [comment]
> @DBrettRobertson could we add an action item about the EEA's devcon workshop? They will be on the call to discuss. Thanks!

Done bud. Have added them as the first agenda item so that they don't have to sit through the whole meeting.

**Comment by timbeiko** [comment]
Another thing to add 😅: helping to organize the [pre-devcon EthMagicians council](https://ethereum-magicians.org/t/council-of-osaka-date-and-place/3367/16).

**Comment by DBrettRobertson** [comment]
Meeting concluded.
