### ISSUE TITLE
Add Tim Beiko to ECH Multisig

### ISSUE THREAD

**Issue by timbeiko** [ethereum-cat-herders/PM#93]
Based on the [Aragon Vote #10](https://mainnet.aragon.org/#/ethereumcatherders/0xe837d5bacfddf6fd0fab88fa314681d7926c7399), no one opposed having me added to the multisig. 

My address is `0x10F5d45854e038071485AC9e402308cF80D2d2fE`.

**Comment by lrettig** [comment]
Confirmed this wallet address with @timbeiko on Gitter, Telegram, Twitter, and Aragon (see images below). Submitted add owner tx: https://etherscan.io/tx/0x33f1c348a66586111c2efae5a6a9dcf59f150f3035a88e674319aa38a55eeed3.

@Souptacular @CPSTL could you please double-check everything and confirm this tx? It should be tx 31 in the multisig.

Thanks!

![image](https://user-images.githubusercontent.com/3316532/66147596-fc8d1a80-e5c3-11e9-9a62-5f708f1e07c6.png)
![image](https://user-images.githubusercontent.com/3316532/66147604-0151ce80-e5c4-11e9-81a0-2392c1805b8e.png)
![image](https://user-images.githubusercontent.com/3316532/66147645-14fd3500-e5c4-11e9-92aa-109a843cf9d1.png)
![image](https://user-images.githubusercontent.com/3316532/66147824-732a1800-e5c4-11e9-8963-e9c8532933d1.png)

**Comment by CPSTL** [comment]
Thanks, Lane. The transaction has been confirmed and Tim has been added: https://etherscan.io/tx/0x485a7993cef3aa559d9e9f35e263355fd0f7c6b70a8a10ba2d73ede023370bc0. Before confirming, I doubled checked with @timbeiko via Twitter, Telegram and referenced the images above as well.
