### ISSUE TITLE
Collecting Funds from Moloch

### ISSUE THREAD

**Issue by CPSTL** [ethereum-cat-herders/PM#94]
Last week, I set up the transaction (Tx 30) on the [multi-sig](https://etherscan.io/address/0x68085e7f88e90fa9247489c83fab30b177ebccb3) to ragequit 16 of the 17 shares the Ethereum Cat Herders were granted from Moloch (leaving 1 share to stay in as a member). This will provide us with 16 WETH. 

**Transaction set up process:**
- Added the moloch contract address as the destination [address](https://etherscan.io/address/0x1fd169a4f5c59acf79d0fd5d91d1201ef1bce9f1).
- Set Amount to 0 
- Added in the Moloch ABI from [here](https://etherscan.io/address/0x1fd169a4f5c59acf79d0fd5d91d1201ef1bce9f1#code)
- Selected the `ragequit` method
- Entered `16` as the parameter for `sharesToBurn`
- Sent multi-sig tx

Please double-check the details before confirming the transaction (cc: @lrettig @Souptacular @timbeiko). Let me know if you have any questions or concerns.

**Comment by timbeiko** [comment]
Here is a link to the ECH multisig, for simplicity: https://etherscan.io/address/0x68085e7f88e90fa9247489c83fab30b177ebccb3

**Comment by timbeiko** [comment]
I approved the transaction with Charles over videoconference. We got the funds 🎉 ! 

Final transaction: https://etherscan.io/tx/0x3dd9db62c211498229a08c3ab2a9f2c9855699a519685eb2fbe843dffb669008
