### ISSUE TITLE
Ethereum Cat Herder Meeting #23: Agenda

### ISSUE THREAD

**Issue by CPSTL** [ethereum-cat-herders/PM#96]
## Date and Time

Tuesday, 26 November 2019 [14:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-ny-new-york-city/2pm) 

## Location 

Zoom: The link has been sent to attendees.
YouTube Recording Link: **TBA**

## Agenda

1. ECH-ETH Magician collaboration 

1. Hard Fork Coordination Update 

1. EIP Improvement Process

1. Migration of DAI and use of DSR/other Savings options 

1. Discuss and close the ECH GitHub Issues/PRs

1. Documentation of the ECH process 

1. Documenting/removing inactive cat herders from the private chat.

- Adding James Hancock to the private chat because he is the new HF coordinator and having direct line to us is beneficial.

8. Discuss the PR to Ethereum.org about ECH page

9. ECH website update

10. Review of outstanding action items 
- Community Initiatives Brainstorming Update
- Confirm all funding/accounting/multisig tasks are completed
- Set up Ethereum Cat Herders Community Bounty (Gitcoin) 
- Ethereum 2.0 Bounties
- ProgPoW community update / ProgPow refund to community members 

11. Any Other Business
- Finalize draft before submission (EthCC Workshop)
- Review community calls transcripts for action items and open issues

**Comment by wschwab** [comment]
One of the things that came up on the EF call was documentation of the ECH process - writing down how we do things. The idea was that it could help foster more communication. Can we bring that up?

**Comment by timbeiko** [comment]
@wschwab IIRC @poojaranjan has done some work on this.

**Comment by timbeiko** [comment]
Last call to review the [EthCC Workshop proposal](https://docs.google.com/document/d/1ErKyuxWtu1mw_mRVO5luu00K08m4ou5KEAAdz0Ifgwc/edit?usp=sharing). I'll submit it after the next call to give everyone a chance to review one more time.

**Comment by poojaranjan** [comment]
@wschwab @timbeiko 
Yes, we have some documentation available at [ECH GitHub](https://github.com/ethereum-cat-herders/PM) like
- [Contribution Guideline](https://github.com/ethereum-cat-herders/PM/blob/master/Contribution_Guidelines.md)
- [Meeting notes process and template](https://github.com/ethereum-cat-herders/PM/blob/master/Meeting_Notes_Template.md)
- [ECH Task list](https://github.com/ethereum-cat-herders/PM/blob/master/ECHTaskList.md)
- [Code of conduct](https://github.com/ethereum-cat-herders/PM/blob/master/CODE_OF_CONDUCT.md)

We can add more as we take ownership of new tasks. Also, I agree, we can keep it as an agenda item to discuss further.

**Comment by Souptacular** [comment]
@timbeiko can you open up the document for comments? It is currently closed.

**Comment by Souptacular** [comment]
I'd like to add the following to the agenda:

- Documenting/removing inactive cat herders from the private chat.
- Adding James Hancock to the chat because he is the new HF coordinator and having direct line to us is beneficial.

**Comment by timbeiko** [comment]
@Souptacular my bad. Link updated!

**Comment by DBrettRobertson** [comment]
Meeting happened November 26, 2019.
